//! Screen mutation requests shared by semantic routing and the Screen owner.

const csi_params = @import("../csi_params.zig");
const cursor = @import("cursor.zig");
const erase = @import("erase.zig");
const rect = @import("rect.zig");
const screen_color = @import("color.zig");

/// One borrowed-or-value mutation request consumed synchronously by Screen.
pub const ScreenAction = union(enum) {
    cursor_up: u16,
    cursor_down: u16,
    cursor_forward: u16,
    cursor_back: u16,
    cursor_next_line: u16,
    cursor_prev_line: u16,
    cursor_horizontal_absolute: u16,
    cursor_vertical_absolute: u16,
    cursor_position: struct { row: u16, col: u16 },
    write_text: []const u8,
    write_codepoint: u21,
    repeat_preceding: u16,
    line_feed,
    next_line,
    reverse_index,
    carriage_return,
    backspace,
    horizontal_tab,
    horizontal_tab_forward: u16,
    horizontal_tab_back: u16,
    horizontal_tab_set,
    tab_clear_current,
    tab_clear_all,
    cursor_visible: bool,
    cursor_style: cursor.CursorStyleCommand,
    cursor_color: ?screen_color.Rgb,
    cursor_text_color: ?screen_color.Rgb,
    auto_wrap: bool,
    origin_mode: bool,
    insert_mode: bool,
    sgr: struct {
        params: []const i32,
        separators: csi_params.CsiSeparatorList,
    },
    insert_lines: u16,
    delete_lines: u16,
    insert_chars: u16,
    delete_chars: u16,
    scroll_up_lines: u16,
    scroll_down_lines: u16,
    set_scroll_region: struct { top: u16, bottom: ?u16 },
    reset_screen,
    erase_display_below: bool,
    erase_display_above: bool,
    erase_display_complete: bool,
    erase_display_scrollback: bool,
    erase_display_scroll_complete: bool,
    erase_line: erase.EraseMode,
    selective_erase_line: erase.EraseMode,
    erase_chars: u16,
    shift_left_columns: u16,
    shift_right_columns: u16,
    character_protection: bool,
    rect_erase: rect.RectArea,
    rect_selective_erase: rect.RectArea,
    rect_fill: struct { area: rect.RectArea, ch: u21 },
    rect_copy: rect.RectCopy,
    rect_attrs_change: struct { area: rect.RectArea, attrs: csi_params.AttrParams, reverse: bool },
    insert_columns: u16,
    delete_columns: u16,
    attr_change_extent_rect: bool,
    left_right_margin_mode: bool,
    set_left_right_margins: struct { left: u16, right: ?u16 },
    reset_default_tab_stops,
};
