const csi_params = @import("csi_params.zig");
const cursor = @import("screen/cursor.zig");
const dcs_payload = @import("dcs_payload.zig");
const erase = @import("screen/erase.zig");
const kitty_protocol = @import("kitty/protocol.zig");
const legacy_control = @import("legacy_control.zig");
const mode = @import("mode.zig");
const rect = @import("screen/rect.zig");
const screen_color = @import("screen/color.zig");
const terminal_color_control = @import("terminal_color_control.zig");

/// Screen-directed semantic event union.
pub const SemanticEvent = union(enum) {
    cursor_up: u16,
    cursor_down: u16,
    cursor_forward: u16,
    cursor_back: u16,
    cursor_next_line: u16,
    cursor_prev_line: u16,
    cursor_horizontal_absolute: u16,
    cursor_vertical_absolute: u16,
    cursor_position: struct { row: u16, col: u16 },
    write_text: []const u8,
    write_codepoint: u21,
    repeat_preceding: u16,
    line_feed,
    next_line,
    reverse_index,
    carriage_return,
    backspace,
    horizontal_tab,
    horizontal_tab_forward: u16,
    horizontal_tab_back: u16,
    horizontal_tab_set,
    tab_clear_current,
    tab_clear_all,
    cursor_visible: bool,
    cursor_style: cursor.CursorStyleCommand,
    cursor_color: ?screen_color.Rgb,
    cursor_text_color: ?screen_color.Rgb,
    reverse_screen_mode: bool,
    auto_wrap: bool,
    origin_mode: bool,
    insert_mode: bool,
    application_cursor_keys: bool,
    application_keypad: bool,
    ansi_mode_set: csi_params.ModeParams,
    ansi_mode_reset: csi_params.ModeParams,
    ansi_mode_query: u16,
    modify_other_keys_set: i8,
    modify_other_keys_query,
    modify_other_keys_disable,
    key_format_change: mode.KeyFormatChange,
    key_format_query: u8,
    pointer_mode: u2,
    kitty_clipboard_mode: bool,
    reverse_wraparound_mode: bool,
    extended_reverse_wraparound_mode: bool,
    focus_reporting: bool,
    bracketed_paste: bool,
    synchronized_output: bool,
    mouse_tracking_off,
    mouse_tracking_x10,
    mouse_tracking_normal,
    mouse_tracking_button_event,
    mouse_tracking_any_event,
    mouse_protocol_utf8: bool,
    mouse_protocol_sgr: bool,
    mouse_protocol_urxvt: bool,
    kitty_keyboard_set: struct { flags: u32, mode: u8 },
    kitty_keyboard_query,
    kitty_keyboard_push: u32,
    kitty_keyboard_pop: u16,
    kitty_shell_mark: kitty_protocol.KittyShellMark,
    kitty_notification: kitty_protocol.KittyNotificationCommand,
    kitty_pointer_shape: kitty_protocol.KittyPointerShapeCommand,
    kitty_color_stack: kitty_protocol.KittyColorStackCommand,
    kitty_multiple_cursor: kitty_protocol.KittyMultipleCursorCommand,
    kitty_file_transfer: []const u8,
    kitty_text_size: []const u8,
    title_set: []const u8,
    color_control: terminal_color_control.TerminalColorControlCommand,
    hyperlink_set: []const u8,
    hyperlink_clear,
    clipboard_set: []const u8,
    dec_mode_query: u16,
    dec_mode_save: csi_params.ModeParams,
    dec_mode_restore: csi_params.ModeParams,
    dcs_request_status: []const u8,
    dcs_request_termcap: []const u8,
    dcs_request_resource: []const u8,
    dcs_payload: dcs_payload.DcsPayload,
    device_status_report,
    dec_device_status_report: u16,
    cursor_position_report,
    dec_cursor_position_report,
    primary_device_attributes,
    secondary_device_attributes,
    tertiary_device_attributes,
    xtversion,
    xttitlepos,
    xtchecksum: u16,
    rect_checksum_request: struct { request_id: u16, page: u16, area: rect.RectArea },
    selected_graphic_rendition_report: rect.RectArea,
    displayed_extent_report,
    parameters_report: u16,
    xtreportcolors,
    locator_reporting: struct { mode: u16, unit: u16 },
    locator_filter: rect.OptionalRectArea,
    locator_events: csi_params.ModeParams,
    locator_request: u16,
    media_copy_request: u16,
    legacy_control: legacy_control.LegacyControlKind,
    sgr: struct {
        params: []const i32,
        separators: csi_params.CsiSeparatorList,
    },
    enter_alt_screen: struct { clear: bool, save_cursor: bool },
    exit_alt_screen: struct { restore_cursor: bool },
    save_cursor,
    restore_cursor,
    insert_lines: u16,
    delete_lines: u16,
    insert_chars: u16,
    delete_chars: u16,
    scroll_up_lines: u16,
    scroll_down_lines: u16,
    set_scroll_region: struct {
        top: u16,
        bottom: ?u16,
    },
    reset_screen,
    erase_display: erase.EraseMode,
    erase_line: erase.EraseMode,
    selective_erase_display: erase.EraseMode,
    selective_erase_line: erase.EraseMode,
    erase_chars: u16,
    shift_left_columns: u16,
    shift_right_columns: u16,
    character_protection: bool,
    rect_erase: rect.RectArea,
    rect_selective_erase: rect.RectArea,
    rect_fill: struct { area: rect.RectArea, ch: u21 },
    rect_copy: rect.RectCopy,
    rect_attrs_change: struct { area: rect.RectArea, attrs: csi_params.AttrParams, reverse: bool },
    insert_columns: u16,
    delete_columns: u16,
    attr_change_extent_rect: bool,
    left_right_margin_mode: bool,
    set_left_right_margins: struct { left: u16, right: ?u16 },
    reset_default_tab_stops,
};
